apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
      name: nginx-deployment
  namespace: wgwtest-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: harbor.myoffice.com/test/nginx
        ports:
        - containerPort: 80
        - containerPort: 443
