apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
      name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: harbor.wgwtest.com/test/nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: "/data/logs"
          name: app-logs
      volumes:
      - name: app-logs
        persistentVolumeClaim:
          claimName: general-pvc
        
