kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
    - ip: 172.16.1.33
    ports:
    - port: 1
  - addresses:
    - ip: 172.16.1.34
    ports:
    - port: 1
  - addresses:
    - ip: 172.16.1.35
    ports:
    - port: 1
