apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnmp-deployment
  labels:
    name: lnmp-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: harbor.office.com/guahao/nginx:v2.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/data/conf"
          name: lnmp-config
        - mountPath: "/data/log"
          name: app-logs
        - mountPath: "/data/wwwroot"
          name: app-logs
        command: ["/usr/local/nginx/sbin/nginx"]
        args: ["-c","/data/conf/nginx.conf"]

      - name: php-container
        image: harbor.office.com/guahao/php:v7.2-ext
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: "/data/conf"
          name: lnmp-config
        - mountPath: "/data/log"
          name: app-logs
        - mountPath: "/data/wwwroot"
          name: app-logs
        command: ["/usr/local/php/sbin/php-fpm"]
        args: ["-c","/data/conf/php.ini","-y","/data/conf/php-fpm.conf"]
 
      volumes:
      - name: lnmp-config
        configMap:
          name: lnmp-config
      - name: app-logs
        persistentVolumeClaim:
          claimName: general-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: lnmp-svc
  labels:
    app: lnmp-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
    name: tcp
  selector:
    app: nginx-pod
  
